### ISSUE TITLE
接线问题

### ISSUE THREAD

**Issue by starlight-w** [EriciusX/MAX30102#1]
oled 和心率传感器模块的接线是啥？我看不明白求告知

**Comment by EriciusX** [comment]
见README

**Comment by xlxychao** [comment]
引脚可以在iic.h里改，但似乎oled和max30102的接口共用？没怎么看懂，还在尝试

**Comment by EriciusX** [comment]
oled的SCL为PC12，SDA为PC11，MAX30102的INT引脚为PB5
